name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Change to e2e directory
        run: cd e2e
      - name: Install dependencies
        run: npm install
      - name: Build and start
        run: |
          npm run build
          npm start
