name: Cypress Tests

on:
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instale o pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Instale as dependências NPM, faça o cache corretamente
      # e execute todos os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./e2e
          run: ls -la
          build: npm run build
          start: npm start
